[project]
name = "riscv-analyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyparsing>=3.2.3",
    "typer>=0.16.0",
]
